#page title
page_title                                : IPTV - Streams                            # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : #1234793120                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : IPTV - Streams                            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your last IPTV app.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : André Martingo                              
your_link                                 : https://github.com/andremartingo                   
your_city                                 : Berlin                                
email_address                             : appiptvstreams@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : andremartingo
github_username                           : andremartingo
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Aesthetic Design
    description                           : Not just how it looks – but also how it works, and how it feels.
    fontawesome_icon_name                 : mobile

  - title                                 : More Formats
    description                           : We don't just support m3u8! We support m3u8, mp4, mkv, mpv, 3gp, ts and much more.
    fontawesome_icon_name                 : file-video

  - title                                 : Smart Import
    description                           : It's easy to import a list of channels with us. Paste the link we take care of the rest!
    fontawesome_icon_name                 : file-download
  
  - title                                 : iCloud Sync
    description                           : When create a new reminder it will sync with your currently reminders.
    fontawesome_icon_name                 : cloud

  - title                                 : Continuous Updates
    description                           : We are continuously working to improve the app. Give us your feedback.
    fontawesome_icon_name                 : sync

  - title                                 : Privacy is protected
    description                           : The contents of your playlist are never sent to our servers. You channels are only viewable on your own devices.
    fontawesome_icon_name                 : user-secret

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.1
topbar_title_color                        : "#000000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#fafafa"

link_color                                : "#FE8000"

app_title_color                           : "#000000"
app_price_color                           : "#666666"
app_description_color                     : "#666666"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FE8000"
feature_icons_background_color            : "#ffffff"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown